### ISSUE TITLE
Interested in the details of each step

### ISSUE THREAD

**Issue by ptrckstuns** [v-iashin/WebsiteYOLO#48]
:> Would like to do the same.

**Comment by v-iashin** [comment]
Hi,

I have not noticed the title of this issue before and couldn't figure out what you want. I see now.
I will try to compose some details and release them soon. Stay tuned.

**Comment by tommyngx** [comment]
please explain the steps as details as you can. 
I love what you did for this project. Thank you so so much for your sharing and time.
I appreciate your work!
Keep up with your nice code!

**Comment by v-iashin** [comment]
Ok,

Here it is: https://v-iashin.github.io/how_did_you_build_your_detector
