### ISSUE TITLE
API?

### ISSUE THREAD

**Issue by Mapsama** [v-iashin/WebsiteYOLO#49]
Hi, awesome work!
Are you going to offer an api for the YOLO-results in json?
This would be great to use the results (position and object-name) for a lot of projects.

Regards

**Comment by v-iashin** [comment]
Hi, thanks.

Most likely not. 

You can do it on your premises. There are plenty of out-of-the-box solutions. For example, [torchvision models](https://pytorch.org/vision/stable/models.html#object-detection-instance-segmentation-and-person-keypoint-detection).

Good luck!
